language: python
python:
  - "2.7"
services:
  - couchdb
before_install:
  - easy_install -U setuptools
install:
  - pip install -r test_requirements.txt --use-mirrors
  - python setup.py develop
script:
  - nosetests
after_success:
  - coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/15e2534ac51757c92e72
    on_success: always
    on_failure: always
    on_start: false
