language: python
sudo: false
python:
  - "2.7"
services:
  - couchdb
cache:
  directories:
    - eggs
before_install:
  - pip install setuptools==7.0
  - python2 bootstrap.py
install:
  - bin/buildout -N
script:
  - bin/nosetests
after_success:
  - bin/coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/15e2534ac51757c92e72
    on_success: always
    on_failure: always
    on_start: false
